packages:
  - name: brrss
    environment:
      API_KEY: "${API_KEY}"
    functions:
      - name: main
        main: Main
        runtime: go:1.20
        web: raw
        limits:
          memory: 128
          timeout: 3000
          logs: 1024
